#' Plot number of peaks
#'
#' Plot the average number of peaks detected per well
#'
#' @param peak_stats A peaks stats data frame generated by \code{\link{get_stats}}
#' @param peaks The dataframe with detected peaks generated by \code{\link{detect_peaks}}
#'
#' @import ggplot2
#'
#' @export
plot_number_of_peaks = function(peak_stats, peaks) {
  cols = colorRampPalette(brewer.pal(11, "Spectral"))(50)
  peaks %>% ungroup() %>% group_by(Well) %>% count(Well, Label) %>% ungroup() %>%
    mutate(Well = factor(Well, levels = peak_stats$Well)) %>%
    ggplot(aes(x = Well, y = n)) + geom_boxplot(aes(fill = ..middle..)) +
    scale_fill_gradientn(colours = cols) +
    theme_bw() + labs(y = "Number of Peaks") +
    theme(legend.position = "none")
}

#' Plot width of peaks
#'
#' Plot the average width of peaks detected per well
#'
#' @param peak_stats A peaks stats data frame generated by \code{\link{get_stats}}
#' @param peaks The dataframe with detected peaks generated by \code{\link{detect_peaks}}
#'
#' @export
plot_width_of_peaks = function(peak_stats, peaks) {

  cols = colorRampPalette(brewer.pal(11, "Spectral"))(50)
  peaks %>% ungroup() %>% group_by(Well) %>%  ungroup() %>%
    mutate(Well = factor(Well, levels = peak_stats$Well)) %>%
    ggplot(aes(x = Well, y = Width)) +
    geom_boxplot(aes(fill = ..middle..)) +
    scale_fill_gradientn(colours = cols) + theme_bw() +
    labs(y = "Width of Peaks (min)")

}

#' Plot individual tracks
#'
#' Plot the individual tracks of a well with the option to show peaks and to show only tracks with
#' detected peaks
#'
#' @param data The raw data, usually baseline corrected with \code{\link{baseline_correct}}
#' @param well The well to plot
#' @param y The name of the y-axis
#' @param peak_data For showing peaks, generated by \code{\link{detect_peaks}}
#' @param filter_peaks logical Show only spots with detected peaks
#' @param show_peaks logical Show detected peaks in plot
#'
#' @return a ggplot object
#' @export
plot_tracks = function(data, well = "All", y = "Intensity", peak_data = NULL,
                       filter_peaks = FALSE, show_peaks = TRUE) {
  if(!"All" %in% well){
    data  = data %>%  filter(Well %in% well)
    peak_data = peak_data %>% filter(Well %in% well)
  }

  if (filter_peaks && !is.null(peak_data)) {
    data = data %>% semi_join(peak_data, by = c("Well", "Label"))
  }

  num_sec = length(unique(data$Well))
  cols = colorRampPalette(brewer.pal(9, "Set1"))(num_sec + 1)

  plot = data %>%
    ggplot(aes_string(x = "Time", y = y , group = "Label", colour = "Well")) +
    geom_line() +
    facet_wrap(Well ~ Label, labeller = labeller(.default = label_value, .multi_line = FALSE)) +
    scale_colour_manual(values = cols[2:length(cols)]) +
    theme_bw() +
    theme(panel.margin = unit(0, "lines"), strip.background  = element_rect(fill = "grey95")) +
    labs(x = "Time (min)")

  if (show_peaks && !is.null(peak_data) ) {
    plot = plot + geom_point(data = peak_data, colour = cols[1])

  }

  return(plot)

}
